// src/modules/Footer.tsx
import { FaLinkedin, FaInstagram } from 'react-icons/fa';
import fsek from '../assets/fseklogga.svg';
import { t } from 'i18next';

function Footer() {
    return (
      <footer className="grid grid-cols-3 gap-4 content-center w-full">
        <div className="mx-16 my-10 flex justify-start space-x-6">
          <a
            href="https://www.linkedin.com/company/f-sek-farad"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Linkedin"
            className="text-black hover:text-blue-500 transition-colors"
          >
            <FaLinkedin className="h-12 w-12" />
          </a>
          <a
            href="https://instagram.com/fsek_farad"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Instagram"
            className="text-black hover:text-pink-500 transition-colors"
          >
            <FaInstagram className="h-12 w-12" />
          </a>
        </div>
        <div className="text-center my-6 font-bold">
          <div className="text-2xl">{t("contact")}:</div>
          <a href="mailto:farad@fsektionen.se" className="text-black text-2xl font-bold hover:text-gray-300">farad@fsektionen.se</a>
        </div>
        <a href="https://fsektionen.se/" className="flex justify-end">
          <img src={fsek} alt="Logo" className="h-20 my-4 mx-8" />
        </a>
      </footer>
      );
}

export default Footer;

// src/components/Footer.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages';
	import { routes } from '$lib/routes';
	import Fsek from './Fsek.svelte';

	const groups = [
		{
			title: m.navigate(),
			links: [
				{
					name: m.home,
					href: '/'
				},
				...routes
			]
		},
		{
			title: m.follow_us(),
			links: [
				{ name: 'Instagram', href: 'https://instagram.com/fsek_farad' },
				{ name: 'LinkedIn', href: 'https://www.linkedin.com/company/f-sek-farad' }
			]
		},
		{
			title: m.contact_us(),
			links: [
				{
					name: 'farad@fsektionen.se',
					href: 'mailto:farad@fsektionen.se'
				}
			]
		}
	] as const;
</script>

<footer class="border-t border-neutral-200 bg-neutral-50">
	<div class="mx-auto flex max-w-6xl flex-wrap gap-8 px-4 py-16">
		{#each groups as group (group.title)}
			<div class="basis-40 md:basis-64">
				<h3 class="font-medium">{group.title}</h3>
				<ul>
					{#each group.links as { name, href } (href)}
						<li class="my-2">
							<a {href} class="text-neutral-700 hover:text-black hover:underline"
								>{typeof name === 'function' ? name() : name}</a
							>
						</li>
					{/each}
				</ul>
			</div>
		{/each}
		<!--
		<p class="text-md text-center font-medium">
			<a href="mailto:farad@fsektionen.se" class="hover:underline">farad@fsektionen.se</a>
		</p> -->

		<a href="https://fsektionen.se" class="ml-auto flex flex-col gap-8">
			<Fsek className="h-32 text-forange" />
		</a>
	</div>
</footer>
